// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhiC0lZBY2pCHBFiFUjmYmfnrH2iWaHn0',
    appId: '1:189019405559:web:e447041c7f628b21e7e7f2',
    messagingSenderId: '189019405559',
    projectId: 'expense-tracker-6e129',
    authDomain: 'expense-tracker-6e129.firebaseapp.com',
    databaseURL: 'https://expense-tracker-6e129-default-rtdb.firebaseio.com',
    storageBucket: 'expense-tracker-6e129.firebasestorage.app',
    measurementId: 'G-3G7DZFSCS8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAp_QPpyqVVOonEVen9hM-LlJ0Demy-Ql8',
    appId: '1:189019405559:android:91060892325e2f0ae7e7f2',
    messagingSenderId: '189019405559',
    projectId: 'expense-tracker-6e129',
    databaseURL: 'https://expense-tracker-6e129-default-rtdb.firebaseio.com',
    storageBucket: 'expense-tracker-6e129.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeS_tt8o34qkUmhSEy02TkvkANm-ECxz0',
    appId: '1:189019405559:ios:fbd87586301eab10e7e7f2',
    messagingSenderId: '189019405559',
    projectId: 'expense-tracker-6e129',
    databaseURL: 'https://expense-tracker-6e129-default-rtdb.firebaseio.com',
    storageBucket: 'expense-tracker-6e129.firebasestorage.app',
    iosClientId:
        '189019405559-q8oohndqgbl6l235hrcr60qbtmkee7kg.apps.googleusercontent.com',
    iosBundleId: 'com.example.expenseTracker',
  );
}
